### ISSUE TITLE
asciidoc.css not found - custom theme can not be fully applied

### ISSUE THREAD

**Issue by stmon** [asciidoc-py/asciidoc-py#27]
When trying to specify custom css file, style is just partially applied:
CMD: `python asciidoc.py -a stylesheet=my_styles/my_style.css doc/asciidoc.txt`
after adding the path to stylesheets directory WARNING is displayed and no output is generated:
CMD: `python asciidoc.py -a stylesheet=my_styles/my_style.css -a stylesdir=my_styles doc/asciidoc.txt`
WARNING: `include file not found: {working_dir}\my_styles\asciidoc.css`

Problem could be solved if I rename `my_style.css` to `asciidoc.css` and adding both arguments `stylesheet` and `stylesdir` when calling asciidoc.py from CLI.

**Comment by elextr** [comment]
Don't know what you mean by "just partly applied".

When you specify the `stylesheet` attribute its an additional stylesheet, it does not replace asciidoc.css so that is included as well.  The extra stylesheet overrides only those elements of the standard style that it changes by the magic of cascading stylesheets.  When you specify `stylesdir` the `asciidoc.css` is expected to be in that directory, so its not found.

**Comment by stmon** [comment]
with partly applied I mean that some parts of document are having correct styling but some not. Tables should be:
![image](https://user-images.githubusercontent.com/1108331/41958202-9d3e4866-79e9-11e8-8ac8-8e93866ad331.png)
but instead it's look like this:
![image](https://user-images.githubusercontent.com/1108331/41958311-f2519394-79e9-11e8-83c7-708480f59f71.png)
Probably is just my non-understanding  how the themes works in asciidoc and how must be prepared.
I pick the themes from https://github.com/darshandsoni/asciidoctor-skins.

**Comment by elextr** [comment]
That repository has no connection to Asciidoc itself, so its probably best to discuss it there.
