### ISSUE TITLE
Header Syntax

### ISSUE THREAD

**Issue by GSebastian-Adil** [asciidoc-py/asciidoc-py#47]
To clarify the syntax of header I made this example and I want your opinion.
Thanks
[Header'Syntax.txt](https://github.com/asciidoc/asciidoc-py3/files/2570033/Header.Syntax.txt)

**Comment by elextr** [comment]
Some comments:

1. The title can also be specified as `= title` rather than underlined.  Underlined titles are deprecated because its counting is dodgy for anything but ASCII.

2. Your author matches the Asciidoc documentation, so thats fine

3. The revision is ok, but you don't specify how the remark is terminated.

**Comment by GSebastian-Adil** [comment]
From the documentation the entire header is ended by a "blank line", But I don't know how symbolize a "blank line", so I tried this example. For the header I _personally_ prefer this syntax.
[Header_0.2.txt](https://github.com/asciidoc/asciidoc-py3/files/2572197/Header_0.2.txt)

**Comment by elextr** [comment]
The revision remark can also be terminated by (at least) attribute entries and comments.

**Comment by GSebastian-Adil** [comment]
I added attribute entry (but I don't know its syntax) and comment.
[Header_0.3.txt](https://github.com/asciidoc/asciidoc-py3/files/2582867/Header_0.3.txt)
